In [5]:
import numpy as np
x = np.array ([[1,2,3],
               [4,5,6],
               [7,8,9]])
y = x[0,:]

print (x)

print (y.size)
print (y)
y = np.expand_dims(y,axis=0)
print (y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[1 2 3]
[[1 2 3]]


In [8]:
z = np.expand_dims(x[1,:], axis= 0)

In [9]:
w = y*z
print (w)

[[ 4 10 18]]


In [10]:
print (np.linalg.norm(x))

16.881943016134134


In [12]:
print (np.linalg.norm(x/x[-1,:]))

2.087012058198457
